blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/flagit/flagit/discussions
    about: Ask a question or start a discussion instead of opening an issue.
